### ISSUE TITLE
Structure of Apex test cases around Exception handling

### ISSUE THREAD

**Issue by FishOfPrey** [trailheadapps/dreamhouse-sfdx#65]
The style of the Apex automated tests was brought up on the Salesforce StackExchange - [Using try, catch and finally in test class (dreamhouseapp)](https://salesforce.stackexchange.com/q/243730/102). 

The tests presented in, say, PropertyControllerTest.cls are misleading to new developers about the objective of running the test cases beyond raw code coverage. 

E.g.

```
static testMethod void testgetPropertyList() {
        Boolean success = true;
        try {
            Property__c p = new Property__c(Location__Latitude__s=-71.110448,Location__Longitude__s=42.360642);
            insert p;
	        PropertyController.getPropertyList('', 0, 1000000, 0, 0, '');
        } catch (Exception e) {
            success = false;
        } finally {
	        System.assert(success);
        }
    }
```

If you compare that to the actual [PropertyController.getPropertyList() method](https://github.com/dreamhouseapp/dreamhouse-sfdx/blob/1548d38e8bbb59600160dea7bf4d6d01ab6a6aab/force-app/main/default/classes/PropertyController.cls#L4) it isn't clear what is being tested beyond raw coverage.

Some potential issues:

1. The getPropertyList() method doesn't throw any specific exceptions, which is all the test is asserting for.
1. If an exception was thrown, any details about what the exception was would be lost
1. There are no assertions made that the method returned the expected values.
1. There is no validation of the various parameters that can be passed to the method.

These would necessitate a range of tests for the method in question rather than the current one. However, I think it is important to demonstrate good testing practices beyond a basic smoke test that provides coverage.

**Comment by albarivas** [comment]
I've posted this issue on the dreamhouse-lwc version as we don't update this one anymore, and I'll take care of it @FishOfPrey https://github.com/trailheadapps/dreamhouse-lwc/issues/150
